version: '3.9'
services:
  users-service-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bebolder 
      MYSQL_DATABASE: users-service-db
    ports:
      - "3306:3306"
    volumes:
      - ./users_service_mysql:/var/lib/mysql
  vacation-requests-service-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bebolder
      MYSQL_DATABASE: vacation-requests-service-db
    ports:
      - "3307:3306"
    volumes:
      - ./vacation_request_service_mysql:/var/lib/mysql
  notification-service-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bebolder
      MYSQL_DATABASE: notification-service-db
    ports:
      - "3308:3306"
    volumes:
      - ./notification_service_mysql:/var/lib/mysql 
volumes:
  users_service_mysql:
  vacation_request_service_mysql:
  notification_service_mysql:

      